services:
  - docker
language: go
sudo: required
go:
  - "1.11.x"
dist: xenial

before_install:
  - openssl aes-256-cbc -K $encrypted_877ffd1bc544_key -iv $encrypted_877ffd1bc544_iv -in scripts/gogetcookie.sh.enc -out scripts/gogetcookie.sh -d

install:
  - bash scripts/gogetcookie.sh
  - go get github.com/kardianos/govendor

script:
  - bash scripts/startk3s_ci.sh
  - make build
  - KUBECONFIG=/etc/rancher/k3s/k3s.yaml make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_deploy:
  - make build-binaries
  - git tag "v0.3.$TRAVIS_BUILD_NUMBER"
  - export BODY=$(git log -1 --pretty='%s')

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    # yamllint disable rule:line-length
    secure: I8bwlu7hA95SjGdM4bgotMSnShahYX8Z8yb7XSB/gbuKvf/BjTu4Rr+tkZ5/bI16jYqHxBB4yPbzQ0sOU4vaYIcfTFORMQVfF+2vqQowILwWkyEkdSLcQhlCfnF1gfKcnmkJb39GLZZ2MOl6ZEje9MMZrB2jAAGL903rVTAFRoQ97/cmv5QLFxfLKzXL9j6ZTte3QBwJCKMl3bsVW6SN/f8t5ZDl8sc0plvy/yeNfGO5qrsRs8dsSVSfzt8fIltiLLza9SU2EQ/U3t0mzAXWyldGiG20eNPuWRD5906ET4hqXLTjhV9rUPGTYx6/Fuf0lixjrY5p8CL4ofC6FMH6kEweFY6nfRNMny9mFB+C5i4REOwhep0BPt5jURtQdIvO5ulhuzKH+kh9bIMGSIUJ/+9dQzquMZDuWmuNlbK7ZGhL3I1/rYEOP88GtQLqrCD37I8mu0JxCzqQVqj0oke8Qe6roR5mvyK11Nf7Z2Wu0ydc6CNPOuC6+swo/YbqySIDBpTXKiFrbSwHHeEjsZY8rODJe5oLHv+R33k8lbl2gLqeQG2UrwSZQL53SOsrHz/Bv2LPtgUx/LgYAUO5QeM48QttCLb4Xi2lSLcONn7qWa074OerbfXL8wx/J37Ix5Qz2kWdL/MGFYvEzQP7mzzb60Mt87oMLUAY9Y1YMZvJ4GI=
  file_glob: true
  file: bin/*
  body: ${BODY}
  # yamllint disable-line rule:truthy
  on:
    repo: gavinbunney/terraform-provider-kubernetes-yaml
    branch: master
